# Credit-SME Risk Analytics Dashboard
#
# The app reads the reproducible SQLite and model artifacts generated by the
# project scripts. Run the data, analysis, and model pipelines before startup.

suppressPackageStartupMessages({
  library(DBI)
  library(RSQLite)
  library(dplyr)
  library(readr)
  library(shiny)
  library(bslib)
})

project_root <- normalizePath(getwd(), winslash = "/", mustWork = TRUE)
sqlite_path <- file.path(project_root, "data", "processed", "give_me_some_credit.sqlite")
required_artifacts <- c(
  sqlite_path,
  file.path(project_root, "models", "logistic_model.rds"),
  file.path(project_root, "models", "model_preprocessor.rds"),
  file.path(project_root, "reports", "generated", "model_metrics.csv"),
  file.path(project_root, "reports", "generated", "model_calibration.csv"),
  file.path(project_root, "reports", "generated", "model_lift_by_decile.csv"),
  file.path(project_root, "reports", "generated", "model_threshold_metrics.csv"),
  file.path(project_root, "reports", "generated", "model_roc_curves.csv"),
  file.path(project_root, "reports", "generated", "numeric_group_comparisons.csv"),
  file.path(project_root, "reports", "generated", "missingness.csv"),
  file.path(project_root, "reports", "generated", "segment_default_rates.csv"),
  file.path(project_root, "reports", "generated", "correlation_matrix_spearman.csv"),
  file.path(project_root, "reports", "generated", "monitoring_summary.csv"),
  file.path(project_root, "reports", "generated", "monitoring_distributions.csv"),
  file.path(project_root, "reports", "generated", "monitoring_psi.csv"),
  file.path(project_root, "reports", "generated", "monitoring_feature_drift.csv"),
  file.path(project_root, "reports", "generated", "monitoring_calibration.csv")
)
missing_artifacts <- required_artifacts[!file.exists(required_artifacts)]
if (length(missing_artifacts) > 0) {
  stop(
    "Dashboard artifacts are missing. Run `Rscript R/data_cleaning.R`, `Rscript R/statistical_analysis.R`, and `Rscript R/train_models.R` first. Missing: ",
    paste(missing_artifacts, collapse = ", "),
    call. = FALSE
  )
}

source(file.path(project_root, "R", "feature_engineering.R"))

db_connection <- DBI::dbConnect(RSQLite::SQLite(), sqlite_path)
cleaned_data <- DBI::dbReadTable(db_connection, "training_clean")
model_metrics <- readr::read_csv(
  file.path(project_root, "reports", "generated", "model_metrics.csv"),
  show_col_types = FALSE
)
model_calibration <- readr::read_csv(
  file.path(project_root, "reports", "generated", "model_calibration.csv"),
  show_col_types = FALSE
)
model_lift <- readr::read_csv(
  file.path(project_root, "reports", "generated", "model_lift_by_decile.csv"),
  show_col_types = FALSE
)
model_thresholds <- readr::read_csv(
  file.path(project_root, "reports", "generated", "model_threshold_metrics.csv"),
  show_col_types = FALSE
)
model_roc_curves <- readr::read_csv(
  file.path(project_root, "reports", "generated", "model_roc_curves.csv"),
  show_col_types = FALSE
)
numeric_comparisons <- readr::read_csv(
  file.path(project_root, "reports", "generated", "numeric_group_comparisons.csv"),
  show_col_types = FALSE
)
missingness <- readr::read_csv(
  file.path(project_root, "reports", "generated", "missingness.csv"),
  show_col_types = FALSE
)
segment_rates <- readr::read_csv(
  file.path(project_root, "reports", "generated", "segment_default_rates.csv"),
  show_col_types = FALSE
)
correlation_data <- readr::read_csv(
  file.path(project_root, "reports", "generated", "correlation_matrix_spearman.csv"),
  show_col_types = FALSE
)
monitoring_summary <- readr::read_csv(
  file.path(project_root, "reports", "generated", "monitoring_summary.csv"),
  show_col_types = FALSE
)
monitoring_distributions <- readr::read_csv(
  file.path(project_root, "reports", "generated", "monitoring_distributions.csv"),
  show_col_types = FALSE
)
monitoring_psi <- readr::read_csv(
  file.path(project_root, "reports", "generated", "monitoring_psi.csv"),
  show_col_types = FALSE
)
monitoring_feature_drift <- readr::read_csv(
  file.path(project_root, "reports", "generated", "monitoring_feature_drift.csv"),
  show_col_types = FALSE
)
monitoring_calibration <- readr::read_csv(
  file.path(project_root, "reports", "generated", "monitoring_calibration.csv"),
  show_col_types = FALSE
)
logistic_model <- readRDS(file.path(project_root, "models", "logistic_model.rds"))
model_preprocessor <- readRDS(file.path(project_root, "models", "model_preprocessor.rds"))

model_features <- build_model_features(cleaned_data)
model_features <- apply_model_preprocessor(model_features, model_preprocessor)
cleaned_data$predicted_risk <- as.numeric(stats::predict(
  logistic_model,
  newdata = model_features,
  type = "response"
))

assign_risk_band <- function(score, reference_scores = cleaned_data$predicted_risk) {
  reference_scores <- sort(reference_scores[is.finite(reference_scores)])
  percentile <- findInterval(score, reference_scores, left.open = FALSE) / length(reference_scores)
  factor(
    dplyr::case_when(
      percentile <= 0.50 ~ "Low",
      percentile <= 0.80 ~ "Moderate",
      percentile <= 0.95 ~ "High",
      TRUE ~ "Very high"
    ),
    levels = c("Low", "Moderate", "High", "Very high")
  )
}

cleaned_data$risk_band <- assign_risk_band(cleaned_data$predicted_risk)
cleaned_data$age_band <- cut(
  cleaned_data$age,
  breaks = c(-Inf, 29, 44, 59, Inf),
  labels = c("<30", "30-44", "45-59", "60+"),
  right = TRUE
)
cleaned_data$age_band <- as.character(cleaned_data$age_band)
cleaned_data$age_band[is.na(cleaned_data$age_band)] <- "Missing"
cleaned_data$income_status <- ifelse(
  cleaned_data$monthly_income_missing == 1,
  "Missing",
  "Observed"
)
cleaned_data$delinquency_90_status <- dplyr::case_when(
  is.na(cleaned_data$number_of_times90days_late) ~ "Missing",
  cleaned_data$number_of_times90days_late > 0 ~ "One or more 90+ day events",
  TRUE ~ "No 90+ day events"
)

pretty_feature_labels <- c(
  age = "Age",
  log_revolving_utilization = "Revolving utilization",
  log_debt_ratio = "Debt ratio",
  log_monthly_income = "Monthly income",
  open_credit_lines = "Open credit lines",
  times_30_59 = "30-59 days late",
  times_60_89 = "60-89 days late",
  times_90 = "90+ days late",
  real_estate_loans = "Real-estate loans",
  dependents = "Dependents",
  age_missing = "Age missing",
  monthly_income_missing = "Monthly income missing",
  dependents_missing = "Dependents missing",
  time_30_59_missing = "30-59-day history missing",
  time_60_89_missing = "60-89-day history missing",
  time_90_missing = "90-day history missing",
  revolving_utilization_gt_1 = "Utilization above 1",
  debt_ratio_gt_10 = "Debt ratio above 10"
)

model_display_labels <- c(
  Logistic = "Logistic",
  Logistic_WOE = "Logistic (WoE)",
  CART = "CART",
  RandomForest = "Random Forest",
  XGBoost = "XGBoost"
)

stat_distribution_variables <- c(
  "Age" = "age",
  "Monthly income" = "monthly_income",
  "Debt ratio" = "debt_ratio",
  "Revolving utilization" = "revolving_utilization_of_unsecured_lines",
  "Open credit lines" = "number_of_open_credit_lines_and_loans",
  "30-59 days late" = "number_of_time30_59days_past_due_not_worse",
  "60-89 days late" = "number_of_time60_89days_past_due_not_worse",
  "90+ days late" = "number_of_times90days_late",
  "Dependents" = "number_of_dependents"
)

monitoring_feature_labels <- c(
  age = "Age",
  monthly_income = "Monthly income",
  debt_ratio = "Debt ratio",
  revolving_utilization_of_unsecured_lines = "Revolving utilization",
  number_of_open_credit_lines_and_loans = "Open credit lines",
  number_of_time30_59days_past_due_not_worse = "30-59 days late",
  number_of_time60_89days_past_due_not_worse = "60-89 days late",
  number_of_times90days_late = "90+ days late",
  number_real_estate_loans_or_lines = "Real-estate loans",
  number_of_dependents = "Dependents"
)

format_number <- function(value, digits = 0) {
  ifelse(
    is.na(value),
    "—",
    formatC(value, format = "f", digits = digits, big.mark = ",")
  )
}

format_percentage <- function(value, digits = 1) {
  ifelse(
    is.na(value),
    "—",
    paste0(formatC(value * 100, format = "f", digits = digits), "%")
  )
}

metric_card <- function(label, value, note) {
  tags$div(
    class = "metric-card",
    tags$div(class = "metric-label", label),
    tags$div(class = "metric-value", value),
    tags$div(class = "metric-note", note)
  )
}

page_intro <- function(kicker, title, description) {
  tags$div(
    class = "page-intro",
    tags$div(class = "page-kicker", kicker),
    tags$h1(title),
    tags$p(description)
  )
}

plot_theme <- function() {
  graphics::par(
    col = "#252821",
    col.axis = "#252821",
    col.lab = "#252821",
    col.main = "#252821",
    fg = "#606C38",
    bg = "#E8DCC7",
    mar = c(5, 5, 3, 2)
  )
}

app_css <- "
  :root {
    --sand: #E8DCC7;
    --oat: #D4B895;
    --sage: #8B9D83;
    --clay: #B08B6E;
    --terracotta: #C66B3D;
    --ochre: #C08E3A;
    --moss: #606C38;
    --ink: #252821;
    --white: #F7F3EA;
  }

  body {
    background: var(--sand);
    color: var(--ink);
    font-family: 'Trebuchet MS', Arial, sans-serif;
    font-size: 15px;
  }

  body::before {
    content: '';
    position: fixed;
    inset: 0;
    pointer-events: none;
    opacity: 0.025;
    background-image: url(\"data:image/svg+xml,%3Csvg viewBox='0 0 160 160' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.8' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='.5'/%3E%3C/svg%3E\");
    z-index: 10;
  }

  .navbar {
    background: var(--moss);
    border: 0;
    border-radius: 0 0 18px 18px;
    box-shadow: 0 6px 18px rgba(37, 40, 33, 0.16);
  }

  .navbar-default .navbar-brand,
  .navbar-default .navbar-nav > li > a {
    color: var(--white);
  }

  .navbar-default .navbar-nav > li > a:hover,
  .navbar-default .navbar-nav > .active > a,
  .navbar-default .navbar-nav > .active > a:hover {
    color: var(--ink);
    background: var(--oat);
  }

  .navbar-brand {
    font-family: Georgia, serif;
    font-size: 20px;
    letter-spacing: -0.02em;
  }

  .container-fluid {
    max-width: 1500px;
    padding: 28px 34px 48px;
  }

  .page-intro {
    padding: 24px 4px 22px;
    border-bottom: 1px solid rgba(96, 108, 56, 0.35);
    margin-bottom: 24px;
  }

  .page-intro h1 {
    font-family: Georgia, serif;
    font-size: clamp(30px, 4vw, 54px);
    line-height: 1.02;
    letter-spacing: -0.04em;
    margin: 4px 0 10px;
    color: var(--ink);
  }

  .page-intro p {
    max-width: 720px;
    font-size: 16px;
    line-height: 1.55;
    margin: 0;
  }

  .page-kicker {
    color: var(--terracotta);
    font-size: 12px;
    font-weight: 700;
    letter-spacing: 0.08em;
    text-transform: uppercase;
  }

  .panel,
  .well,
  .metric-card,
  .notice,
  .simulator-result {
    background: rgba(247, 243, 234, 0.78);
    border: 1px solid rgba(96, 108, 56, 0.35);
    border-radius: 18px;
    box-shadow: 0 8px 22px rgba(37, 40, 33, 0.08);
  }

  .panel {
    padding: 18px 20px 20px;
    margin-bottom: 22px;
  }

  .panel h3 {
    font-family: Georgia, serif;
    font-size: 22px;
    margin: 0 0 5px;
  }

  .panel-caption {
    color: #60645A;
    font-size: 13px;
    margin-bottom: 15px;
  }

  .metric-grid {
    display: grid;
    grid-template-columns: repeat(4, minmax(0, 1fr));
    gap: 14px;
    margin-bottom: 22px;
  }

  .metric-card {
    padding: 18px 20px;
    border-left: 6px solid var(--terracotta);
  }

  .metric-label {
    color: #60645A;
    font-size: 12px;
    font-weight: 700;
    letter-spacing: 0.05em;
    text-transform: uppercase;
  }

  .metric-value {
    font-family: Georgia, serif;
    font-size: 34px;
    line-height: 1.1;
    margin: 6px 0;
  }

  .metric-note {
    color: #60645A;
    font-size: 12px;
  }

  .notice {
    padding: 16px 18px;
    background: var(--oat);
    border-color: rgba(192, 142, 58, 0.58);
    margin: 12px 0 22px;
  }

  .notice strong { color: var(--ink); }

  .form-control,
  .selectize-input,
  .selectize-control.single .selectize-input {
    background: var(--white);
    border: 1px solid rgba(96, 108, 56, 0.5);
    border-radius: 10px;
    color: var(--ink);
  }

  .control-label {
    color: var(--moss);
    font-weight: 700;
  }

  .btn-primary {
    background: var(--terracotta);
    border-color: var(--terracotta);
    border-radius: 10px;
  }

  .btn-primary:hover,
  .btn-primary:focus {
    background: var(--ochre);
    border-color: var(--ochre);
  }

  .table {
    background: var(--white);
    border-radius: 12px;
    overflow: hidden;
  }

  .table > thead > tr > th {
    background: var(--moss);
    color: var(--white);
    border: 0;
  }

  .table > tbody > tr > td { border-color: rgba(96, 108, 56, 0.18); }

  .risk-result {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 16px;
    align-items: stretch;
  }

  .risk-score,
  .risk-band {
    padding: 22px;
    border-radius: 16px;
    background: var(--moss);
    color: var(--white);
  }

  .risk-score .value,
  .risk-band .value {
    font-family: Georgia, serif;
    font-size: 36px;
    margin-top: 5px;
  }

  .risk-band { background: var(--terracotta); }

  .shiny-plot-output,
  .plot-output {
    background: var(--sand);
    border-radius: 14px;
  }

  @media (max-width: 900px) {
    .metric-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); }
    .risk-result { grid-template-columns: 1fr; }
    .container-fluid { padding: 20px 16px 36px; }
  }

  @media (max-width: 560px) {
    .metric-grid { grid-template-columns: 1fr; }
  }
"

theme <- bslib::bs_theme(
  version = 5,
  bg = "#E8DCC7",
  fg = "#252821",
  primary = "#606C38",
  secondary = "#B08B6E",
  success = "#606C38",
  warning = "#C08E3A",
  danger = "#C66B3D",
  base_font = bslib::font_collection("Trebuchet MS", "Arial", "sans-serif"),
  heading_font = bslib::font_collection("Georgia", "serif")
)

ui <- shiny::tagList(
  shiny::tags$head(shiny::tags$style(shiny::HTML(app_css))),
  shiny::navbarPage(
    title = shiny::tags$span("SME Risk Analytics"),
    id = "main_nav",
    theme = theme,
    tabPanel(
      "Overview",
      page_intro(
        "Give Me Some Credit / portfolio view",
        "A clear view of borrower risk.",
        "Explore default patterns, risk-band mix, and segment movement in the cleaned training portfolio. All risk outputs are demonstrations based on the public dataset."
      ),
      sidebarLayout(
        sidebarPanel(
          class = "panel",
          h3("Portfolio filters"),
          div(class = "panel-caption", "Filters apply to the borrower-level training portfolio."),
          selectInput("overview_age", "Age band", choices = c("All", "<30", "30-44", "45-59", "60+", "Missing")),
          selectInput("overview_income", "Monthly income", choices = c("All", "Observed", "Missing")),
          selectInput("overview_delinquency", "90+ day history", choices = c("All", "No 90+ day events", "One or more 90+ day events", "Missing"))
        ),
        mainPanel(
          uiOutput("overview_cards"),
          div(class = "notice", strong("Responsible use: "), "This dashboard is an educational demonstration. It is not a lending-policy engine and should not be used to approve or decline real applications."),
          fluidRow(
            column(6, div(class = "panel", h3("Risk-band distribution"), div(class = "panel-caption", "Bands are percentile-based demonstrations from the saved logistic model."), plotOutput("overview_risk_bands", height = "320px"))),
            column(6, div(class = "panel", h3("Default rate by age"), div(class = "panel-caption", "Observed target rate with borrower counts shown in the chart."), plotOutput("overview_age_default", height = "320px")))
          ),
          div(class = "panel", h3("Filtered portfolio summary"), div(class = "panel-caption", "The target is SeriousDlqin2yrs: serious delinquency within two years."), tableOutput("overview_summary_table"))
        )
      )
    ),
    tabPanel(
      "Portfolio performance",
      page_intro(
        "Portfolio performance",
        "Find the segments carrying the signal.",
        "Compare observed default rates across borrower attributes available in the Give Me Some Credit data. Application dates, loan amounts, industry, and geography are not present in this source."
      ),
      sidebarLayout(
        sidebarPanel(
          class = "panel",
          h3("Segment view"),
          div(class = "panel-caption", "Choose a real source field or a model-derived demonstration band."),
          selectInput("portfolio_group", "Group by", choices = c("Age band" = "age_band", "Income availability" = "income_status", "90+ day history" = "delinquency_90_status", "Risk band" = "risk_band"))
        ),
        mainPanel(
          div(class = "panel", h3(textOutput("portfolio_panel_title", inline = TRUE)), div(class = "panel-caption", "Observed default rate and borrower count."), plotOutput("portfolio_segment_plot", height = "380px")),
          div(class = "panel", h3("Segment table"), tableOutput("portfolio_segment_table"))
        )
      )
    ),
    tabPanel(
      "Statistical analysis",
      page_intro(
        "Statistical analysis",
        "Separate pattern from policy.",
        "Descriptive comparisons, missingness, correlation, confidence intervals, and chi-square tests are shown as sample associations. They do not establish causality."
      ),
      div(
        class = "panel",
        h3("Distribution explorer"),
        div(class = "panel-caption", "Choose a source field to compare its observed distribution across the target classes. Values remain on the source scale and outliers are retained in the summaries."),
        selectInput("stat_distribution_variable", "Source field", choices = stat_distribution_variables),
        plotOutput("stat_distribution", height = "380px")
      ),
      fluidRow(
        column(6, div(class = "panel", h3("Missingness"), div(class = "panel-caption", "Source fields with missing values after cleaning."), plotOutput("stat_missingness", height = "360px"))),
        column(6, div(class = "panel", h3("Spearman correlation"), div(class = "panel-caption", "Pairwise-complete numeric observations."), plotOutput("stat_correlation", height = "360px")))
      ),
      div(class = "panel", h3("Defaulted vs. non-defaulted borrowers"), div(class = "panel-caption", "Medians and Wilcoxon p-values are shown because several fields are skewed."), tableOutput("stat_numeric_table")),
      div(class = "panel", h3("Selected segment confidence intervals"), div(class = "panel-caption", "Wilson 95% intervals for age, income, and dependents groupings."), tableOutput("stat_segment_table"))
    ),
    tabPanel(
      "Credit model",
      page_intro(
        "Credit-scoring model",
        "Rank risk, inspect the trade-offs.",
        "The saved logistic baseline is compared with a WoE logistic candidate, CART, a class-balanced Random Forest benchmark, and XGBoost on the same held-out test set. Metrics are demonstrations, not validated lending-policy thresholds."
      ),
      uiOutput("model_recommendation"),
      div(class = "panel", h3("Held-out model comparison"), div(class = "panel-caption", "ROC-AUC and PR-AUC reward ranking quality; Brier score rewards probability accuracy."), tableOutput("model_metrics_table")),
      fluidRow(
        column(6, div(class = "panel", h3("ROC comparison"), plotOutput("model_roc", height = "360px"))),
        column(6, div(class = "panel", h3("Calibration by risk decile"), plotOutput("model_calibration_plot", height = "360px")))
      ),
      div(class = "panel", h3("Lift by risk decile"), div(class = "panel-caption", "Decile 1 contains the highest predicted-risk borrowers."), plotOutput("model_lift_plot", height = "360px")),
      div(class = "panel", h3("Demonstration threshold trade-offs"), div(class = "panel-caption", "No threshold is selected as real lending policy."), tableOutput("model_threshold_table")),
      div(class = "notice", strong("Model boundary: "), "The current comparison includes raw logistic, WoE logistic, CART, Random Forest, and XGBoost. The class-weighted ensembles have poor probability calibration and are not production models.")
    ),
    tabPanel(
      "Monitoring",
      page_intro(
        "Model monitoring",
        "Watch the evidence, name the gap.",
        "This page demonstrates prediction drift, feature drift, and calibration checks using the fixed Phase 3 train/test split. The source data has no application date, so these are non-temporal diagnostics rather than production alerts."
      ),
      div(class = "notice", strong("Monitoring boundary: "), "No synthetic monitoring rows or simulated time periods were generated. PSI thresholds are screening heuristics and must be calibrated against timestamped operational history before use."),
      fluidRow(
        column(6, div(class = "panel", h3("Prediction distribution"), div(class = "panel-caption", "Reference train versus comparison test; both are analytical slices, not calendar periods."), plotOutput("monitoring_prediction_plot", height = "360px"))),
        column(6, div(class = "panel", h3("Feature PSI"), div(class = "panel-caption", "Population Stability Index from reference-train quantile bins. Lower values indicate more similar distributions in this demonstration."), plotOutput("monitoring_psi_plot", height = "360px")))
      ),
      div(class = "panel", h3("Monitoring scope"), tableOutput("monitoring_summary_table")),
      div(class = "panel", h3("Feature drift summary"), div(class = "panel-caption", "Mean differences can be influenced by extreme values; median and missingness changes are shown alongside PSI."), tableOutput("monitoring_feature_table")),
      div(class = "panel", h3("Logistic calibration check"), div(class = "panel-caption", "Decile 1 contains the highest predicted-risk borrowers. This is a non-temporal demonstration comparison."), tableOutput("monitoring_calibration_table"))
    ),
    tabPanel(
      "Risk simulator",
      page_intro(
        "Applicant risk simulator",
        "Test the saved preprocessing path.",
        "Enter borrower attributes to run the same feature engineering and logistic model used by the portfolio analysis. The result is for demonstration only."
      ),
      sidebarLayout(
        sidebarPanel(
          class = "panel",
          h3("Borrower attributes"),
          numericInput("sim_age", "Age", value = 45, min = 18, max = 100, step = 1),
          numericInput("sim_utilization", "Revolving utilization", value = 0.35, min = 0, step = 0.01),
          numericInput("sim_debt_ratio", "Debt ratio", value = 0.40, min = 0, step = 0.01),
          checkboxInput("sim_income_missing", "Monthly income unavailable", value = FALSE),
          numericInput("sim_income", "Monthly income", value = 5000, min = 0, step = 100),
          numericInput("sim_open_lines", "Open credit lines and loans", value = 8, min = 0, step = 1),
          numericInput("sim_30_59", "30-59 days late count", value = 0, min = 0, step = 1),
          numericInput("sim_60_89", "60-89 days late count", value = 0, min = 0, step = 1),
          numericInput("sim_90", "90+ days late count", value = 0, min = 0, step = 1),
          numericInput("sim_real_estate", "Real-estate loans or lines", value = 1, min = 0, step = 1),
          checkboxInput("sim_dependents_missing", "Dependents unavailable", value = FALSE),
          numericInput("sim_dependents", "Dependents", value = 0, min = 0, step = 1)
        ),
        mainPanel(
          div(class = "panel", h3("Demonstration result"), uiOutput("simulator_result")),
          div(class = "panel", h3("Model contribution view"), div(class = "panel-caption", "These are directional contributions from the saved logistic terms, not causal explanations."), tableOutput("simulator_drivers")),
          div(class = "notice", strong("Responsible use: "), "Do not use this simulator to make or support a real credit decision. The source data is public, historical, and not a complete SME application record.")
        )
      )
    )
  )
)

server <- function(input, output, session) {
  overview_data <- reactive({
    data <- cleaned_data
    if (input$overview_age != "All") data <- data[data$age_band == input$overview_age, , drop = FALSE]
    if (input$overview_income != "All") data <- data[data$income_status == input$overview_income, , drop = FALSE]
    if (input$overview_delinquency != "All") data <- data[data$delinquency_90_status == input$overview_delinquency, , drop = FALSE]
    data
  })

  output$overview_cards <- renderUI({
    data <- overview_data()
    default_rate <- if (nrow(data) > 0) mean(data$serious_dlqin2yrs) else NA_real_
    high_rate <- if (nrow(data) > 0) mean(data$risk_band %in% c("High", "Very high")) else NA_real_
    tagList(
      div(class = "metric-grid",
        metric_card("Borrowers", format_number(nrow(data)), "Filtered training records"),
        metric_card("Observed default rate", format_percentage(default_rate), "SeriousDlqin2yrs = 1"),
        metric_card("Mean predicted risk", format_percentage(mean(data$predicted_risk), 2), "Saved logistic model"),
        metric_card("High / very high", format_percentage(high_rate), "Demonstration risk bands")
      )
    )
  })

  output$overview_risk_bands <- renderPlot({
    data <- overview_data()
    counts <- table(factor(data$risk_band, levels = c("Low", "Moderate", "High", "Very high")))
    plot_theme()
    graphics::barplot(
      counts,
      col = c("#8B9D83", "#C08E3A", "#B08B6E", "#C66B3D"),
      names.arg = names(counts),
      ylab = "Borrower count",
      main = paste0("Risk bands (n = ", format_number(nrow(data)), ")")
    )
  }, res = 110)

  output$overview_age_default <- renderPlot({
    data <- overview_data()
    if (nrow(data) == 0) {
      plot_theme()
      graphics::plot.new()
      graphics::title("No borrowers match the selected filters.")
      return(invisible(NULL))
    }
    summary <- data |>
      dplyr::group_by(age_band) |>
      dplyr::summarise(borrower_count = dplyr::n(), default_rate = mean(serious_dlqin2yrs), .groups = "drop") |>
      dplyr::mutate(age_band = factor(age_band, levels = c("<30", "30-44", "45-59", "60+", "Missing"))) |>
      dplyr::arrange(age_band)
    plot_theme()
    locations <- graphics::barplot(
      summary$default_rate * 100,
      names.arg = summary$age_band,
      col = "#606C38",
      ylab = "Observed default rate (%)",
      main = "Default rate by age band",
      ylim = c(0, max(summary$default_rate * 100) * 1.28)
    )
    graphics::text(
      locations,
      summary$default_rate * 100,
      labels = paste0(format_percentage(summary$default_rate), " (n=", format_number(summary$borrower_count), ")"),
      pos = 3,
      cex = 0.75
    )
  }, res = 110)

  output$overview_summary_table <- renderTable({
    data <- overview_data()
    if (nrow(data) == 0) return(data.frame(Message = "No borrowers match the selected filters."))
    data |>
      dplyr::group_by(risk_band) |>
      dplyr::summarise(
        Borrowers = dplyr::n(),
        `Observed default rate` = format_percentage(mean(serious_dlqin2yrs)),
        `Mean predicted risk` = format_percentage(mean(predicted_risk), 2),
        .groups = "drop"
      ) |>
      dplyr::rename(`Risk band` = risk_band)
  }, striped = TRUE, bordered = FALSE, spacing = "s", rownames = FALSE)

  output$portfolio_panel_title <- renderText({
    choices <- c(
      age_band = "Default rate by age band",
      income_status = "Default rate by income availability",
      delinquency_90_status = "Default rate by 90+ day history",
      risk_band = "Default rate by demonstration risk band"
    )
    choices[[input$portfolio_group]]
  })

  portfolio_summary <- reactive({
    data <- cleaned_data
    group <- input$portfolio_group
    data |>
      dplyr::group_by(.data[[group]]) |>
      dplyr::summarise(
        borrower_count = dplyr::n(),
        default_count = sum(serious_dlqin2yrs == 1),
        default_rate = mean(serious_dlqin2yrs),
        mean_predicted_risk = mean(predicted_risk),
        .groups = "drop"
      ) |>
      dplyr::rename(segment = all_of(group)) |>
      dplyr::arrange(dplyr::desc(default_rate))
  })

  output$portfolio_segment_plot <- renderPlot({
    summary <- portfolio_summary()
    plot_theme()
    locations <- graphics::barplot(
      summary$default_rate * 100,
      names.arg = summary$segment,
      col = "#C66B3D",
      ylab = "Observed default rate (%)",
      main = "Observed default rate",
      ylim = c(0, max(summary$default_rate * 100) * 1.28),
      las = 2
    )
    graphics::text(
      locations,
      summary$default_rate * 100,
      labels = paste0(format_percentage(summary$default_rate), " (n=", format_number(summary$borrower_count), ")"),
      pos = 3,
      cex = 0.75
    )
  }, res = 110)

  output$portfolio_segment_table <- renderTable({
    portfolio_summary() |>
      dplyr::mutate(
        default_rate = format_percentage(default_rate),
        mean_predicted_risk = format_percentage(mean_predicted_risk, 2)
      ) |>
      dplyr::rename(
        Segment = segment,
        Borrowers = borrower_count,
        Defaults = default_count,
        `Observed default rate` = default_rate,
        `Mean predicted risk` = mean_predicted_risk
      )
  }, striped = TRUE, bordered = FALSE, spacing = "s", rownames = FALSE)

  output$stat_missingness <- renderPlot({
    values <- missingness |>
      dplyr::filter(missing_count > 0) |>
      dplyr::arrange(missing_pct)
    labels <- c(
      monthly_income = "Monthly income",
      number_of_dependents = "Dependents",
      number_of_time30_59days_past_due_not_worse = "30-59 days late",
      number_of_times90days_late = "90+ days late",
      number_of_time60_89days_past_due_not_worse = "60-89 days late",
      age = "Age"
    )
    plot_theme()
    graphics::barplot(
      values$missing_pct * 100,
      names.arg = unname(labels[values$variable]),
      horiz = TRUE,
      las = 1,
      col = "#B08B6E",
      xlab = "Missing rows (%)",
      main = "Source missingness"
    )
  }, res = 110)

  output$stat_distribution <- renderPlot({
    variable <- input$stat_distribution_variable
    if (is.null(variable) || !variable %in% unname(stat_distribution_variables)) {
      variable <- unname(stat_distribution_variables[[1]])
    }
    label <- names(stat_distribution_variables)[match(variable, stat_distribution_variables)]
    values <- cleaned_data[[variable]]
    target <- cleaned_data$serious_dlqin2yrs
    keep <- is.finite(values) & !is.na(target)

    plot_theme()
    if (!any(keep)) {
      graphics::plot.new()
      graphics::title(main = paste("Distribution of", label), sub = "No finite observations available")
      return(invisible(NULL))
    }

    group <- factor(
      ifelse(target[keep] == 1, "Defaulted", "Non-defaulted"),
      levels = c("Non-defaulted", "Defaulted")
    )
    distribution_values <- values[keep]
    counts <- table(group)
    graphics::boxplot(
      distribution_values ~ group,
      col = c("#8B9D83", "#C66B3D"),
      ylab = "Source value",
      main = paste("Distribution of", label),
      outline = FALSE
    )
    graphics::mtext(
      paste0("Non-missing n: ", format_number(length(distribution_values)), " | ", paste(names(counts), counts, sep = " n=", collapse = "; ")),
      side = 3,
      line = 0.2,
      cex = 0.75,
      col = "#60645A"
    )
  }, res = 110)

  output$stat_correlation <- renderPlot({
    matrix <- as.matrix(correlation_data[, -1])
    rownames(matrix) <- correlation_data$variable
    labels <- unname(pretty_feature_labels[colnames(matrix)])
    plot_theme()
    graphics::par(mar = c(10, 10, 3, 2))
    graphics::image(
      seq_len(ncol(matrix)),
      seq_len(nrow(matrix)),
      matrix[nrow(matrix):1, , drop = FALSE],
      col = grDevices::colorRampPalette(c("#2166ac", "#F7F3EA", "#C66B3D"))(100),
      zlim = c(-1, 1),
      axes = FALSE,
      main = "Spearman correlation"
    )
    graphics::axis(1, at = seq_along(labels), labels = labels, las = 2, cex.axis = 0.7)
    graphics::axis(2, at = seq_along(labels), labels = rev(labels), las = 2, cex.axis = 0.7)
  }, res = 110)

  output$stat_numeric_table <- renderTable({
    numeric_comparisons |>
      dplyr::select(variable, n_nonmissing, mean_defaulted, mean_non_defaulted, median_defaulted, median_non_defaulted, wilcoxon_p_value) |>
      dplyr::mutate(
        variable = unname(pretty_feature_labels[variable]),
        mean_defaulted = format_number(mean_defaulted, 2),
        mean_non_defaulted = format_number(mean_non_defaulted, 2),
        median_defaulted = format_number(median_defaulted, 2),
        median_non_defaulted = format_number(median_non_defaulted, 2),
        wilcoxon_p_value = ifelse(wilcoxon_p_value < 1e-6, "<1e-6", formatC(wilcoxon_p_value, format = "f", digits = 4))
      ) |>
      dplyr::rename(
        Variable = variable,
        `Non-missing` = n_nonmissing,
        `Mean defaulted` = mean_defaulted,
        `Mean non-defaulted` = mean_non_defaulted,
        `Median defaulted` = median_defaulted,
        `Median non-defaulted` = median_non_defaulted,
        `Wilcoxon p-value` = wilcoxon_p_value
      )
  }, striped = TRUE, bordered = FALSE, spacing = "s", rownames = FALSE)

  output$stat_segment_table <- renderTable({
    segment_rates |>
      dplyr::filter(segment %in% c("age_band", "income_band", "dependents_band")) |>
      dplyr::mutate(
        default_rate = format_percentage(default_rate),
        ci = paste0(format_percentage(default_rate_ci_lower), " to ", format_percentage(default_rate_ci_upper))
      ) |>
      dplyr::select(segment, band, borrower_count, default_rate, ci) |>
      dplyr::rename(
        Segment = segment,
        Band = band,
        Borrowers = borrower_count,
        `Default rate` = default_rate,
        `Wilson 95% interval` = ci
      )
  }, striped = TRUE, bordered = FALSE, spacing = "s", rownames = FALSE)

  output$monitoring_prediction_plot <- renderPlot({
    values <- monitoring_psi |>
      dplyr::filter(metric_type == "prediction", variable == "predicted_risk")
    plot_theme()
    graphics::par(mar = c(8, 5, 3, 2))
    distribution_matrix <- rbind(values$reference_pct, values$comparison_pct)
    graphics::barplot(
      distribution_matrix,
      beside = TRUE,
      names.arg = values$bin,
      col = c("#8B9D83", "#C66B3D"),
      border = NA,
      las = 2,
      ylab = "Share of non-missing scores",
      main = "Prediction distribution by reference bin"
    )
    graphics::legend(
      "topright",
      legend = c("Reference train", "Comparison test"),
      fill = c("#8B9D83", "#C66B3D"),
      bty = "n"
    )
  }, res = 110)

  output$monitoring_psi_plot <- renderPlot({
    values <- monitoring_feature_drift |>
      dplyr::arrange(psi) |>
      dplyr::slice_tail(n = min(10, nrow(monitoring_feature_drift)))
    plot_theme()
    graphics::par(mar = c(5, 13, 3, 2))
    graphics::barplot(
      rev(values$psi),
      names.arg = unname(monitoring_feature_labels[rev(values$variable)]),
      horiz = TRUE,
      las = 1,
      col = "#B08B6E",
      border = NA,
      xlab = "PSI",
      main = "Feature distribution shift",
      cex.names = 0.8
    )
    graphics::abline(v = 0.10, lty = 2, col = "#C08E3A")
  }, res = 110)

  output$monitoring_summary_table <- renderTable({
    monitoring_summary |>
      dplyr::rename(
        Check = check,
        Status = status,
        Details = details
      )
  }, striped = TRUE, bordered = FALSE, spacing = "s", rownames = FALSE)

  output$monitoring_feature_table <- renderTable({
    monitoring_feature_drift |>
      dplyr::slice_head(n = 10) |>
      dplyr::mutate(
        variable = unname(monitoring_feature_labels[variable]),
        reference_mean = format_number(reference_mean, 3),
        comparison_mean = format_number(comparison_mean, 3),
        reference_median = format_number(reference_median, 3),
        comparison_median = format_number(comparison_median, 3),
        psi = format_number(psi, 4),
        missing_rate_difference = format_percentage(missing_rate_difference, 2)
      ) |>
      dplyr::select(variable, reference_mean, comparison_mean, reference_median, comparison_median, missing_rate_difference, psi, psi_interpretation) |>
      dplyr::rename(
        Feature = variable,
        `Reference mean` = reference_mean,
        `Comparison mean` = comparison_mean,
        `Reference median` = reference_median,
        `Comparison median` = comparison_median,
        `Missing-rate change` = missing_rate_difference,
        PSI = psi,
        Interpretation = psi_interpretation
      )
  }, striped = TRUE, bordered = FALSE, spacing = "s", rownames = FALSE)

  output$monitoring_calibration_table <- renderTable({
    monitoring_calibration |>
      dplyr::filter(period == "comparison_test") |>
      dplyr::mutate(
        predicted_default_rate = format_percentage(predicted_default_rate),
        observed_default_rate = format_percentage(observed_default_rate),
        calibration_gap = format_percentage(calibration_gap),
        absolute_calibration_gap = format_percentage(absolute_calibration_gap)
      ) |>
      dplyr::select(decile, borrower_count, predicted_default_rate, observed_default_rate, calibration_gap, absolute_calibration_gap) |>
      dplyr::rename(
        Decile = decile,
        Borrowers = borrower_count,
        `Predicted default rate` = predicted_default_rate,
        `Observed default rate` = observed_default_rate,
        `Calibration gap` = calibration_gap,
        `Absolute gap` = absolute_calibration_gap
      )
  }, striped = TRUE, bordered = FALSE, spacing = "s", rownames = FALSE)

  output$model_recommendation <- renderUI({
    woe_metrics <- model_metrics[model_metrics$model == "Logistic_WOE", , drop = FALSE]
    xgb_metrics <- model_metrics[model_metrics$model == "XGBoost", , drop = FALSE]
    if (nrow(woe_metrics) == 0 || nrow(xgb_metrics) == 0) {
      return(div(class = "notice", strong("Held-out interpretation: "), "Model comparison artifacts are incomplete."))
    }

    div(
      class = "notice",
      strong("Held-out interpretation: "),
      paste0(
        "WoE logistic is the strongest interpretable demonstration candidate (ROC-AUC ",
        format_number(woe_metrics$roc_auc[[1]], 3),
        "; Brier score ",
        format_number(woe_metrics$brier_score[[1]], 3),
        "). XGBoost has the best ranking result (ROC-AUC ",
        format_number(xgb_metrics$roc_auc[[1]], 3),
        ") but weaker probability accuracy (Brier score ",
        format_number(xgb_metrics$brier_score[[1]], 3),
        ") after class weighting. These results are held-out demonstrations, not lending policy."
      )
    )
  })

  output$model_metrics_table <- renderTable({
    model_metrics |>
      dplyr::mutate(
        model = unname(model_display_labels[model]),
        default_rate = format_percentage(default_rate),
        roc_auc = format_number(roc_auc, 3),
        pr_auc = format_number(pr_auc, 3),
        ks = format_number(ks, 3),
        brier_score = format_number(brier_score, 3)
      ) |>
      dplyr::select(model, borrower_count, default_rate, roc_auc, pr_auc, ks, brier_score) |>
      dplyr::rename(
        Model = model,
        `Test borrowers` = borrower_count,
        `Default rate` = default_rate,
        `ROC-AUC` = roc_auc,
        `PR-AUC` = pr_auc,
        KS = ks,
        `Brier score` = brier_score
      )
  }, striped = TRUE, bordered = FALSE, spacing = "s", rownames = FALSE)

  output$model_roc <- renderPlot({
    plot_theme()
    colors <- c(Logistic = "#2166ac", Logistic_WOE = "#8c6bb1", CART = "#b2182b", RandomForest = "#606C38", XGBoost = "#C66B3D")
    graphics::plot(
      0,
      0,
      type = "n",
      xlim = c(0, 1),
      ylim = c(0, 1),
      xlab = "False-positive rate",
      ylab = "True-positive rate",
      main = "Held-out ROC comparison"
    )
    for (model_name in unique(model_roc_curves$model)) {
      values <- model_roc_curves[model_roc_curves$model == model_name, , drop = FALSE]
      graphics::lines(
        values$false_positive_rate,
        values$true_positive_rate,
        col = colors[[model_name]],
        lwd = 2
      )
    }
    graphics::abline(0, 1, lty = 2, col = "#8B9D83")
    legend_labels <- paste0(
      unname(model_display_labels[model_metrics$model]),
      " ROC-AUC = ",
      format_number(model_metrics$roc_auc, 3)
    )
    graphics::legend(
      "bottomright",
      legend = legend_labels,
      col = colors[model_metrics$model],
      lwd = 2,
      bty = "n"
    )
  }, res = 110)

  output$model_calibration_plot <- renderPlot({
    plot_theme()
    graphics::plot(0, 0, type = "n", xlim = c(0, max(model_calibration$predicted_default_rate) * 1.05), ylim = c(0, max(model_calibration$observed_default_rate) * 1.05), xlab = "Mean predicted default rate", ylab = "Observed default rate", main = "Calibration by risk decile")
    graphics::abline(0, 1, lty = 2, col = "#8B9D83")
    colors <- c(Logistic = "#2166ac", Logistic_WOE = "#8c6bb1", CART = "#b2182b", RandomForest = "#606C38", XGBoost = "#C66B3D")
    for (model_name in unique(model_calibration$model)) {
      values <- model_calibration[model_calibration$model == model_name, , drop = FALSE]
      graphics::lines(values$predicted_default_rate, values$observed_default_rate, type = "b", col = colors[[model_name]], lwd = 2, pch = 19)
    }
    graphics::legend("topleft", legend = unname(model_display_labels[names(colors)]), col = colors, lwd = 2, pch = 19, bty = "n")
  }, res = 110)

  output$model_lift_plot <- renderPlot({
    plot_theme()
    colors <- c(Logistic = "#2166ac", Logistic_WOE = "#8c6bb1", CART = "#b2182b", RandomForest = "#606C38", XGBoost = "#C66B3D")
    graphics::plot(1:10, rep(NA_real_, 10), type = "n", xlim = c(1, 10), ylim = c(0, max(model_lift$lift) * 1.05), xlab = "Risk decile (1 = highest predicted risk)", ylab = "Observed lift", main = "Lift by risk decile")
    graphics::abline(h = 1, lty = 2, col = "#8B9D83")
    for (model_name in unique(model_lift$model)) {
      values <- model_lift[model_lift$model == model_name, , drop = FALSE]
      graphics::lines(values$decile, values$lift, type = "b", col = colors[[model_name]], lwd = 2, pch = 19)
    }
    graphics::legend("topright", legend = unname(model_display_labels[names(colors)]), col = colors, lwd = 2, pch = 19, bty = "n")
  }, res = 110)

  output$model_threshold_table <- renderTable({
    model_thresholds |>
      dplyr::mutate(
        threshold = format_percentage(threshold),
        sensitivity = format_percentage(sensitivity),
        specificity = format_percentage(specificity),
        precision = format_percentage(precision),
        false_negative_rate = format_percentage(false_negative_rate),
        flagged_rate = format_percentage(flagged_rate)
      ) |>
      dplyr::select(model, threshold, sensitivity, specificity, precision, false_negative_rate, flagged_rate) |>
      dplyr::rename(
        Model = model,
        Threshold = threshold,
        Sensitivity = sensitivity,
        Specificity = specificity,
        Precision = precision,
        `False-negative rate` = false_negative_rate,
        `Flagged rate` = flagged_rate
      )
  }, striped = TRUE, bordered = FALSE, spacing = "s", rownames = FALSE)

  simulator_features <- reactive({
    data.frame(
      age = input$sim_age,
      revolving_utilization_of_unsecured_lines = input$sim_utilization,
      debt_ratio = input$sim_debt_ratio,
      monthly_income = if (isTRUE(input$sim_income_missing)) NA_real_ else input$sim_income,
      number_of_open_credit_lines_and_loans = input$sim_open_lines,
      number_of_time30_59days_past_due_not_worse = input$sim_30_59,
      number_of_time60_89days_past_due_not_worse = input$sim_60_89,
      number_of_times90days_late = input$sim_90,
      number_real_estate_loans_or_lines = input$sim_real_estate,
      number_of_dependents = if (isTRUE(input$sim_dependents_missing)) NA_real_ else input$sim_dependents,
      revolving_utilization_gt_1 = as.integer(input$sim_utilization > 1),
      debt_ratio_gt_10 = as.integer(input$sim_debt_ratio > 10)
    )
  })

  simulator_prediction <- reactive({
    features <- build_model_features(simulator_features())
    processed <- apply_model_preprocessor(features, model_preprocessor)
    score <- as.numeric(stats::predict(logistic_model, newdata = processed, type = "response"))
    list(score = score, band = assign_risk_band(score), features = processed)
  })

  output$simulator_result <- renderUI({
    result <- simulator_prediction()
    div(
      class = "risk-result",
      div(class = "risk-score", div("Predicted probability of serious delinquency"), div(class = "value", format_percentage(result$score, 2)), div("Saved logistic model")),
      div(class = "risk-band", div("Demonstration risk band"), div(class = "value", as.character(result$band)), div("Percentile-based portfolio comparison"))
    )
  })

  output$simulator_drivers <- renderTable({
    result <- simulator_prediction()
    coefficients <- stats::coef(logistic_model)[model_preprocessor$feature_names]
    medians <- model_preprocessor$medians[model_preprocessor$feature_names]
    feature_values <- as.numeric(result$features[1, model_preprocessor$feature_names])
    names(feature_values) <- model_preprocessor$feature_names
    contributions <- (feature_values - medians) * coefficients
    contributions <- sort(contributions[is.finite(contributions)], decreasing = TRUE)
    positive <- head(contributions[contributions > 0], 4)
    negative <- head(contributions[contributions < 0], 2)
    driver_rows <- rbind(
      if (length(positive) > 0) data.frame(Direction = "Higher estimated risk", Feature = names(positive), contribution = unname(positive)) else NULL,
      if (length(negative) > 0) data.frame(Direction = "Lower estimated risk", Feature = names(negative), contribution = unname(negative)) else NULL
    )
    if (is.null(driver_rows) || nrow(driver_rows) == 0) {
      return(data.frame(Message = "No directional contributions available."))
    }
    data.frame(
      Direction = driver_rows$Direction,
      Feature = unname(pretty_feature_labels[driver_rows$Feature]),
      `Relative contribution` = format_number(driver_rows$contribution, 4),
      check.names = FALSE,
      row.names = NULL
    )
  }, striped = TRUE, bordered = FALSE, spacing = "s", rownames = FALSE)
}

shinyApp(ui, server)
