-- Initial KPI queries for data/processed/give_me_some_credit.sqlite.
-- The training_clean table is generated by R/data_cleaning.R.

-- Portfolio size and target prevalence.
SELECT
  COUNT(*) AS borrower_count,
  SUM(CASE WHEN serious_dlqin2yrs = 1 THEN 1 ELSE 0 END) AS default_count,
  AVG(serious_dlqin2yrs) AS default_rate
FROM training_clean;

-- Default distribution.
SELECT
  serious_dlqin2yrs AS default_flag,
  COUNT(*) AS borrower_count,
  COUNT(*) * 1.0 / (SELECT COUNT(*) FROM training_clean) AS portfolio_rate
FROM training_clean
GROUP BY serious_dlqin2yrs
ORDER BY serious_dlqin2yrs;

-- Age-band segment summary.
SELECT
  CASE
    WHEN age < 30 THEN '<30'
    WHEN age < 45 THEN '30-44'
    WHEN age < 60 THEN '45-59'
    WHEN age >= 60 THEN '60+'
    ELSE 'Missing'
  END AS age_band,
  COUNT(*) AS borrower_count,
  AVG(serious_dlqin2yrs) AS default_rate
FROM training_clean
GROUP BY age_band
ORDER BY age_band;

-- Missingness KPIs from the cleaned training table.
SELECT
  variable,
  missing_count,
  row_count,
  missing_pct
FROM missingness
WHERE missing_count > 0
ORDER BY missing_pct DESC;

-- Data-quality flag counts.
SELECT
  metric,
  value
FROM quality_summary
ORDER BY metric;
